<a href="https://colab.research.google.com/github/SU-sumico/edsj/blob/main/2_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###### NumPyの基礎/NumPy basics

* PythonにはNumPyという便利なライブラリがあります。 
* NumPyを利⽤すると、Python標準のリスト型に⽐べて、多次元配列のデータを効率よく扱うことができます。
* NumPyは標準偏差や分散といった統計量を出⼒してくれる関数が⽤意されており、科学技術計算の基盤となっています。
---
* Python has a useful library called NumPy. 
* Using NumPy, you can handle multidimensional array data more efficiently than the standard Python list type.
* NumPy provides functions to output statistics such as standard deviation and variance, and is the basis for scientific and technical calculations.

* Numpyを利⽤するには、まず次のようにインポートを⾏います。
* To use Numpy, first import as follows.

In [ ]:
# Numpyライブラリを、npという別名で使用できるように宣言する
# Declare the Numpy library to be available under the alias np
import numpy as np

* Numpyには、ndarrayと呼ばれるデータ型が⽤意されています。 
* ndarrayは一見すると、Python標準のリスト型（list）と似ていますが、ベクトルや⾏列のように、内部の要素を⼀括して計算できる便利な機能があります。
---
* Numpy provides a data type called ndarray. 
* At first glance, ndarray looks similar to the standard Python list type (list), but it has the useful feature of being able to compute all of its internal elements together, like a vector or an array.

In [ ]:
# arrayを定義する
# Define array
# リスト［1，2，3］をnp.array関数に渡して配列［1, 2, 3］を生成、display関数で表示させています。
# The list [1, 2, 3] is passed to the np.array function to generate the array [1, 2, 3], which is then displayed by the display function.
# display()はdataframe形式の表のレイアウトを保持してくれます。
# display() preserves the layout of the table in dataframe format.

ary = np.array([1, 2, 3])
display( type(ary) )
display( ary )

numpy.ndarray

array([1, 2, 3])

In [ ]:
# aryのすべての要素に5をかける
# Multiply all elements of ary by 5
ary * 5

array([ 5, 10, 15])

* ちなみに同じことをPython標準のリスト型でやろうとすると、全く結果が異なることを確認してみましょう。
* By the way, let's check that if you try to do the same thing with the standard Python list type, the results will be completely different.

In [ ]:
# リスト型の定義の仕方
# How to define list type
lst = [1, 2, 3 ]
lst * 5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

* なお、前述の ary * 5 では、ary内部の値を更新していませんので、もう⼀度ary の中⾝を表⽰させると、[5,10,15]ではなく、[1,2,3]のままなのが確認できます。
* Note that the ary * 5 described above does not update the values inside the ary, so when the ary nave is displayed again, you can see that the values are still [1,2,3] instead of [5,10,15].

In [ ]:
ary

array([1, 2, 3])

* ary内部の値を更新するには、以下のように = を使って、新たな値を代⼊してあげる必要があります。
* この「値を更新したつもりで、実はしていなかった︕」というミスは、プログラミングに慣れるまで（むしろ慣れていても）結構やりがちな失敗なので気をつけましょう。
---
* To update the value inside the ary, a new value must be assigned using = as shown below.
* This mistake, "I thought I updated the value, but actually I didn't︕," is a mistake that people tend to make until they get used to programming (or rather, even if they are used to programming), so be careful.

In [ ]:
ary = ary * 5
ary

array([ 5, 10, 15])

######NumPyでの基礎統計量/Basic statistics in NumPy
* 通常、標準偏差などを計算したい場合は⾃分で実装する必要がありますが、Numpyは基本的な統計量を計算する関数を⽤意しています。
* Normally, if you want to calculate standard deviations, etc., you need to implement the functions yourself. Numpy provides functions to calculate basic statistics.

In [ ]:
# range関数で、0～9までの連続した整数値を生成する
# Generate consecutive integer values from 0 to 9 with the range function.
ary = np.array(range(10))
ary

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# aryの平均値
# Average value of ary
ary.mean()

4.5

In [ ]:
# aryの分散
# ary variance
ary.var()

8.25

In [ ]:
# aryの標準偏差
# Standard deviation of ary
ary.std()

2.8722813232690143

In [ ]:
# aryの最小値
# Minimum value of ary
ary.min()

0

In [ ]:
# aryの最大値
# Maximum value of arry
ary.max()

9