<a href="https://colab.research.google.com/github/su-sumico/edsj/blob/main/2_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPyの基礎
* PythonにはNumPyという便利なライブラリがあります。
* NumPyを利⽤すると、Python標準のリスト型に⽐べて、**多次元配列のデータ**を効率よく扱うことができます。
* NumPyは標準偏差や分散といった統計量を出⼒してくれる関数が⽤意されており、科学技術計算の基盤となっています。
---
NumPy basics
* Python has a useful library called NumPy.
* Using NumPy, you can handle **multidimensional array data** more efficiently than the standard Python list type.
* NumPy provides functions to output statistics such as standard deviation and variance, and is the basis for scientific and technical calculations.

NumPy を使う準備
* Numpyを利⽤するには、まず次のようにインポートを行います。
* モジュール名が長い場合は、import A as B のようにして別名を付けることができます。
---
Prepare to use NumPy
* To use Numpy, first import as follows.
* If the module name is long, it can be aliased as import A as B.

In [ ]:
# Numpyライブラリをnpという別名で使用できるように宣言する
# Declare the Numpy library to be available under the alias np

import numpy as np

多次元配列を定義する

* ベクトル・行列・テンソルなどは、プログラミング上は多次元配列により表現でき、NumPy では **ndarray** というクラスで多次元配列を表現します。
* ndarrayは一見すると、Python標準のリスト型（list）と似ていますが、ベクトルや⾏列のように、内部の要素を⼀括して計算できる便利な機能があります。
* 配列 - array
* 多次元配列 - numpy.ndarray
---
Define multidimensional array

* Vectors, matrices, and tensors can be programmatically represented by multidimensional arrays, and NumPy uses a class called **ndarray** to represent multidimensional arrays.
* At first glance, ndarray looks similar to the standard Python list type (list), but it has the useful feature of being able to compute all of its internal elements together, like a vector or an array.
* Arrays - array
* Multidimensional arrays - numpy.ndarray

* ベクトル・行列・テンソル/Vectors, Matrices, Tensors: https://www.sbbit.jp/article/cont1/63580

numpy.array: https://numpy.org/doc/stable/reference/generated/numpy.array.html

np.array() 関数による生成
* np.array(object, dtype=None)最初の引数 object には、配列の内容を与えます。
* 要素が 1, 2, 3 である長さ 3 の**ベクトル**の例です。
---
Generation by np.array() function
* np.array(object, dtype=None)The first argument object is the contents of the array.
* Here is an example of a **vector** of length 3 with elements 1, 2, 3.

In [ ]:
# ベクトルの定義
# Define vector

ary = np.array([1, 2, 3])

ary

array([1, 2, 3])

* リスト [1, 2, 3] を np.array() に渡すことで、[1,2,3]
 という**ベクトル**を表す ndarray オブジェクトを作ることができます。
* By passing the list [1, 2, 3] to np.array(), we can create an ndarray object that represents **a vector** [1,2,3].

numpy.ndarray: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html

numpy.arrayとnumpy.ndarrayの違い

* numpy.arrayは、numpy.ndarrayを作成するための関数です。
* numpy.ndarrayは、numpyというライブラリが提供する配列です。ndarrayのndは、”N dimension”の省略で、配列を意味する”array”と組み合わせ、「N次元配列」という意味になります。
---
Difference between numpy.array and numpy.ndarray

* numpy.array is a function to create a numpy.ndarray.
* ndarray is an array provided by the numpy library. The "nd" in ndarray is an abbreviation of "N dimension," and combined with "array" meaning an array, it means "N-dimensional array.

In [ ]:
# display()はdataframe形式の表のレイアウトを保持してくれます。
# display() preserves the layout of the table in dataframe format.

display( type(ary) )
display( ary )

numpy.ndarray

array([1, 2, 3])

In [ ]:
# aryのすべての要素に5をかける
# Multiply all elements of ary by 5

ary * 5

array([ 5, 10, 15])

* ちなみに同じことをPython標準のリスト型でやろうとすると、全く結果が異なることを確認してみましょう。
* By the way, let's check that if you try to do the same thing with the standard Python list type, the results will be completely different.

In [ ]:
# リスト型の定義の仕方
# How to define list type

lst = [1, 2, 3 ]
lst * 5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

* なお、前述の ary * 5 では、ary内部の値を更新していませんので、もう⼀度ary の中⾝を表⽰させると、[5,10,15]ではなく、[1,2,3]のままなのが確認できます。
* Note that the ary * 5 described above does not update the values inside the ary, so when the ary nave is displayed again, you can see that the values are still [1,2,3] instead of [5,10,15].

In [ ]:
ary

array([1, 2, 3])

* ary内部の値を更新するには、以下のように = を使って、新たな値を代⼊してあげる必要があります。
* To update the value inside the ary, a new value must be assigned using = as shown below.

In [ ]:
ary = ary * 5
ary

array([ 5, 10, 15])

NumPyでの基礎統計量

* 通常、標準偏差などを計算したい場合は自分で実装する必要がありますが、Numpyは基本的な統計量を計算する関数を用意しています。
---
Basic statistics in NumPy

* Normally, if you want to calculate standard deviations, etc., you need to implement the functions yourself. Numpy provides functions to calculate basic statistics.

連番を生成する

* 連番要素を含むndarrayを生成するとき、Pythonのrangeを使用できます。
---
How to generate sequential numbers

* When generating ndarrays containing sequentially numbered elements, Python's range can be used.

In [ ]:
# range関数で0～9までの連続した整数値を生成する
# Generate consecutive integer values from 0 to 9 with the range function.

ary = np.array(range(10))
ary

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

numpy.mean: https://numpy.org/doc/stable/reference/generated/numpy.mean.html
* numpy.mean()を使うとndarrayの平均値を求められる。
* Using numpy.mean(), the mean value of ndarray can be obtained.

In [ ]:
# aryの平均値
# Average value of ary

np.mean(ary)

4.5

numpy.var: https://numpy.org/doc/stable/reference/generated/numpy.var.html
* numpy.var()を使うとndarrayの分散を求められる。
* Using numpy.var(), the variance of ndarray can be obtained.

In [ ]:
# aryの分散
# ary variance

np.var(ary)

8.25

numpy.std: https://numpy.org/doc/stable/reference/generated/numpy.std.html
* numpy.std()を使うとndarrayの標準偏差を求められる。
* Using numpy.std(), the standard deviation of ndarray can be obtained.

In [ ]:
# aryの標準偏差
# Standard deviation of ary

np.std(ary)

2.8722813232690143

* numpy.min()を使うとndarrayの最小を求められる。
* Using numpy.min(), the minimum of ndarray can be obtained.

In [ ]:
# aryの最小値
# Minimum value of ary

np.min(ary)

0

* numpy.max()を使うとndarrayの最大を求められる。
* Using numpy.max(), the maximum of ndarray can be obtained.

In [ ]:
# aryの最大値
# Maximum value of ary

np.max(ary)

9